# Generated by Django 3.1.7 on 2021-04-15 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
        ('bookmarks', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='bookmark',
            new_name='bookmarks',
        ),
    ]
